### ISSUE TITLE
Version 2.0.0 is not compatible with Cake 0.21.1

### ISSUE THREAD

**Issue by akamud** [cake-contrib/Cake.FileHelpers#17]
When trying to add CakeFileHelpers to a cake file using Cake 0.21.1, I get this error during script addin installation:

```
'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
NuGet exited with 1
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.FileHelpers'.
```

Was this intentional? If so, I didn't see any information about this in the docs.

**Comment by devlead** [comment]
Version 2.0 targets Cake 0.22.0 > which targets .NET 4.6 because that's what latest version of Roslyn requires as Microsoft dropped support for .NET 4.5

If your using an older version of Cake you should clear your tools folder and pin to the previous version and it will still work. 
https://www.nuget.org/packages/Cake.FileHelpers/1.0.4.16

You can read more about pinning Cake and addin versions at

https://cakebuild.net/docs/tutorials/pinning-cake-version

**Comment by akamud** [comment]
Just noticed NuGet shows version 2.0.0 as dependent on Cake 0.22.0.

**Comment by gep13** [comment]
@akamud this should now be taken care of, please let us know if you still have problems.
